### ISSUE TITLE
Stopt working in SS 3.4

### ISSUE THREAD

**Issue by mi32dogs** [silverstripe-australia/silverstripe-grouped-cms-menu#22]
Hi,

it looks like it stoped working in SS 3.4

**Comment by satrun77** [comment]
I think you have subsites module install or another module that override the template LeftAndMain_Menu.ss

I have the same problem, a hotfix for this issue would be to copy the template into mysite folder ./mysite/templates/LeftAndMain_Menu.ss

**Comment by mi32dogs** [comment]
I think you are right, thanks
